[project]
name = "project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "tree-sitter>=0.26.0",
    "tree-sitter-python>=0.25.0",
    "requests>=2.32.0",
    "qdrant-client>=1.10.0",
    "groq>=1.6.0",
    "ragas>=0.4.3",
    "langchain-ollama>=1.1.0",
]
